[tasks.buildprod]
description = "Build BBPlayer production release"
env = { NODE_ENV = "production", BUILD_MODE = "v8a" } 
run = 'eas build --profile prod-v8a --platform android --local --output=./temp-builds/{{arg(name="version")}}-prod.apk'
[tasks.builddev]
description = "Build BBPlayer development release"
env = { NODE_ENV = "development", BUILD_MODE = "v8a" }
run = 'eas build --profile dev --platform android --local --output=./temp-builds/{{arg(name="version")}}-dev.apk'
[env]
_.file = {path = ".env.local", redact = true}