packages:
  - apps/*
  - apps/*/web
  - packages/*
  - packages/*/example
overrides:
  '@expo/config-plugins@8.0.11': 57.0.9
allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  esbuild: true
  lefthook: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
  dtrace-provider: true
  '@fails-components/webtransport-transport-http3-quiche': true
  node-pty: true
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-typescript: true
minimumReleaseAgeExclude:
  - expo-eas-client@57.0.3
  - expo-updates@57.0.23
  - lucide-react@1.39.0
  - '@lodev09/react-native-true-sheet@4.0.0-beta.16'
  - '@legendapp/list@3.4.0'
patchedDependencies:
  '@ark/schema': patches/@ark__schema.patch
  '@expo/ui': patches/@expo__ui.patch
  expo-updates@57.0.23: patches/expo-updates@57.0.23.patch
  metro-runtime@0.84.5: patches/metro-runtime@0.84.5.patch
  metro@0.84.5: patches/metro@0.84.5.patch
  react-native-pager-view@9.0.4: patches/react-native-pager-view@9.0.4.patch
  rn-newarch-svga-player@1.1.16: patches/rn-newarch-svga-player@1.1.16.patch
