packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - esbuild
  - lefthook
  - react-native-logs
  - unrs-resolver

patchedDependencies:
  '@nandorojo/galeria': patches/@nandorojo__galeria.patch
