packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@evilmartians/lefthook'
  - '@firebase/util'
  - '@sentry/cli'
  - '@shopify/react-native-skia'
  - esbuild
  - lefthook
  - protobufjs
  - react-native-logs
  - sharp
  - unrs-resolver
  - workerd
