// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAsset = `-- name: GetAsset :one
SELECT a.object_key,a.content_type,a.size_bytes,u.group_id,u.id,a.is_launch,u.platform,g.runtime_version,g.channel FROM assets a JOIN updates u ON u.id=a.update_id JOIN update_groups g ON g.id=u.group_id WHERE a.id=$1
`

type GetAssetRow struct {
	ObjectKey      string
	ContentType    string
	SizeBytes      int64
	GroupID        pgtype.UUID
	ID             pgtype.UUID
	IsLaunch       bool
	Platform       string
	RuntimeVersion string
	Channel        string
}

func (q *Queries) GetAsset(ctx context.Context, id int64) (GetAssetRow, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i GetAssetRow
	err := row.Scan(
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.GroupID,
		&i.ID,
		&i.IsLaunch,
		&i.Platform,
		&i.RuntimeVersion,
		&i.Channel,
	)
	return i, err
}

const getChannelHead = `-- name: GetChannelHead :one
SELECT mode,group_id FROM channel_heads WHERE channel=$1 AND runtime_version=$2 AND platform=$3
`

type GetChannelHeadParams struct {
	Channel        string
	RuntimeVersion string
	Platform       string
}

type GetChannelHeadRow struct {
	Mode    string
	GroupID pgtype.UUID
}

func (q *Queries) GetChannelHead(ctx context.Context, arg GetChannelHeadParams) (GetChannelHeadRow, error) {
	row := q.db.QueryRow(ctx, getChannelHead, arg.Channel, arg.RuntimeVersion, arg.Platform)
	var i GetChannelHeadRow
	err := row.Scan(&i.Mode, &i.GroupID)
	return i, err
}

const getGroupIDForUpdate = `-- name: GetGroupIDForUpdate :one
SELECT group_id FROM updates WHERE id=$1
`

func (q *Queries) GetGroupIDForUpdate(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGroupIDForUpdate, id)
	var group_id pgtype.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const getUpdateForGroupPlatform = `-- name: GetUpdateForGroupPlatform :one
SELECT u.id,u.launch_key,u.launch_hash,g.created_at FROM updates u JOIN update_groups g ON g.id=u.group_id WHERE u.group_id=$1 AND u.platform=$2
`

type GetUpdateForGroupPlatformParams struct {
	GroupID  pgtype.UUID
	Platform string
}

type GetUpdateForGroupPlatformRow struct {
	ID         pgtype.UUID
	LaunchKey  string
	LaunchHash string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetUpdateForGroupPlatform(ctx context.Context, arg GetUpdateForGroupPlatformParams) (GetUpdateForGroupPlatformRow, error) {
	row := q.db.QueryRow(ctx, getUpdateForGroupPlatform, arg.GroupID, arg.Platform)
	var i GetUpdateForGroupPlatformRow
	err := row.Scan(
		&i.ID,
		&i.LaunchKey,
		&i.LaunchHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets(update_id,asset_key,object_key,sha256,content_type,size_bytes,is_launch) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertAssetParams struct {
	UpdateID    pgtype.UUID
	AssetKey    string
	ObjectKey   string
	Sha256      string
	ContentType string
	SizeBytes   int64
	IsLaunch    bool
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.Exec(ctx, insertAsset,
		arg.UpdateID,
		arg.AssetKey,
		arg.ObjectKey,
		arg.Sha256,
		arg.ContentType,
		arg.SizeBytes,
		arg.IsLaunch,
	)
	return err
}

const listAssetsForUpdate = `-- name: ListAssetsForUpdate :many
SELECT id,asset_key,object_key,sha256,content_type,size_bytes,is_launch FROM assets WHERE update_id=$1 ORDER BY is_launch DESC,id
`

type ListAssetsForUpdateRow struct {
	ID          int64
	AssetKey    string
	ObjectKey   string
	Sha256      string
	ContentType string
	SizeBytes   int64
	IsLaunch    bool
}

func (q *Queries) ListAssetsForUpdate(ctx context.Context, updateID pgtype.UUID) ([]ListAssetsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listAssetsForUpdate, updateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsForUpdateRow
	for rows.Next() {
		var i ListAssetsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetKey,
			&i.ObjectKey,
			&i.Sha256,
			&i.ContentType,
			&i.SizeBytes,
			&i.IsLaunch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
