// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPreviousChannelUpdate = `-- name: GetPreviousChannelUpdate :one
SELECT u.id FROM channel_heads h JOIN updates u ON u.group_id=h.group_id AND u.platform=h.platform WHERE h.channel=$1 AND h.runtime_version=$2 AND h.platform=$3 AND h.mode='ota'
`

type GetPreviousChannelUpdateParams struct {
	Channel        string
	RuntimeVersion string
	Platform       string
}

func (q *Queries) GetPreviousChannelUpdate(ctx context.Context, arg GetPreviousChannelUpdateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPreviousChannelUpdate, arg.Channel, arg.RuntimeVersion, arg.Platform)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertChannelHistory = `-- name: InsertChannelHistory :exec
INSERT INTO channel_history(channel,runtime_version,platform,group_id,mode,action,actor) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertChannelHistoryParams struct {
	Channel        string
	RuntimeVersion string
	Platform       string
	GroupID        pgtype.UUID
	Mode           string
	Action         string
	Actor          pgtype.Text
}

func (q *Queries) InsertChannelHistory(ctx context.Context, arg InsertChannelHistoryParams) error {
	_, err := q.db.Exec(ctx, insertChannelHistory,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
		arg.Mode,
		arg.Action,
		arg.Actor,
	)
	return err
}

const isCompatibleUpdateGroup = `-- name: IsCompatibleUpdateGroup :one
SELECT EXISTS(SELECT 1 FROM updates u JOIN update_groups ug ON ug.id=u.group_id WHERE ug.id=$1 AND ug.channel=$2 AND ug.runtime_version=$3 AND u.platform=$4)
`

type IsCompatibleUpdateGroupParams struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Platform       string
}

func (q *Queries) IsCompatibleUpdateGroup(ctx context.Context, arg IsCompatibleUpdateGroupParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCompatibleUpdateGroup,
		arg.ID,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChannelHeads = `-- name: ListChannelHeads :many
SELECT channel,runtime_version,platform,group_id,mode,updated_at FROM channel_heads ORDER BY channel,runtime_version,platform
`

func (q *Queries) ListChannelHeads(ctx context.Context) ([]ChannelHead, error) {
	rows, err := q.db.Query(ctx, listChannelHeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelHead
	for rows.Next() {
		var i ChannelHead
		if err := rows.Scan(
			&i.Channel,
			&i.RuntimeVersion,
			&i.Platform,
			&i.GroupID,
			&i.Mode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelHeadsByChannel = `-- name: ListChannelHeadsByChannel :many
SELECT runtime_version,platform,group_id,mode,updated_at FROM channel_heads WHERE channel=$1 ORDER BY runtime_version,platform
`

type ListChannelHeadsByChannelRow struct {
	RuntimeVersion string
	Platform       string
	GroupID        pgtype.UUID
	Mode           string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListChannelHeadsByChannel(ctx context.Context, channel string) ([]ListChannelHeadsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listChannelHeadsByChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelHeadsByChannelRow
	for rows.Next() {
		var i ListChannelHeadsByChannelRow
		if err := rows.Scan(
			&i.RuntimeVersion,
			&i.Platform,
			&i.GroupID,
			&i.Mode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelHistory = `-- name: ListChannelHistory :many
SELECT group_id,mode,action,created_at FROM channel_history WHERE channel=$1 ORDER BY created_at DESC
`

type ListChannelHistoryRow struct {
	GroupID   pgtype.UUID
	Mode      string
	Action    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListChannelHistory(ctx context.Context, channel string) ([]ListChannelHistoryRow, error) {
	rows, err := q.db.Query(ctx, listChannelHistory, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelHistoryRow
	for rows.Next() {
		var i ListChannelHistoryRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Mode,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelHead = `-- name: UpsertChannelHead :exec
INSERT INTO channel_heads(channel,runtime_version,platform,group_id,mode) VALUES($1,$2,$3,$4,$5) ON CONFLICT(channel,runtime_version,platform) DO UPDATE SET group_id=excluded.group_id,mode=excluded.mode,updated_at=now()
`

type UpsertChannelHeadParams struct {
	Channel        string
	RuntimeVersion string
	Platform       string
	GroupID        pgtype.UUID
	Mode           string
}

func (q *Queries) UpsertChannelHead(ctx context.Context, arg UpsertChannelHeadParams) error {
	_, err := q.db.Exec(ctx, upsertChannelHead,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
		arg.Mode,
	)
	return err
}
