// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDashboardActivity = `-- name: ListDashboardActivity :many
SELECT day, COALESCE(group_id::text,'')::text AS group_id, count(DISTINCT installation_hmac)::bigint AS active_installations FROM installation_activity_days WHERE day >= $1 AND day < $2 AND channel=$3 AND runtime_version=$4 GROUP BY day, group_id ORDER BY day, group_id
`

type ListDashboardActivityParams struct {
	Day            pgtype.Date
	Day_2          pgtype.Date
	Channel        string
	RuntimeVersion string
}

type ListDashboardActivityRow struct {
	Day                 pgtype.Date
	GroupID             string
	ActiveInstallations int64
}

func (q *Queries) ListDashboardActivity(ctx context.Context, arg ListDashboardActivityParams) ([]ListDashboardActivityRow, error) {
	rows, err := q.db.Query(ctx, listDashboardActivity,
		arg.Day,
		arg.Day_2,
		arg.Channel,
		arg.RuntimeVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardActivityRow
	for rows.Next() {
		var i ListDashboardActivityRow
		if err := rows.Scan(&i.Day, &i.GroupID, &i.ActiveInstallations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardChannelRuntimes = `-- name: ListDashboardChannelRuntimes :many
SELECT h.runtime_version, max(h.updated_at)::timestamptz AS updated_at, (array_agg(g.expo_config->>'version' ORDER BY h.updated_at DESC))[1]::text AS version, COALESCE((array_agg(h.group_id ORDER BY h.updated_at DESC))[1]::text,'')::text AS head_group_id, (array_agg(h.mode ORDER BY h.updated_at DESC))[1]::text AS mode, array_agg(h.platform ORDER BY h.platform)::text[] AS platforms FROM channel_heads h LEFT JOIN update_groups g ON g.id=h.group_id WHERE h.channel=$1 GROUP BY h.runtime_version ORDER BY max(h.updated_at) DESC
`

type ListDashboardChannelRuntimesRow struct {
	RuntimeVersion string
	UpdatedAt      pgtype.Timestamptz
	Version        string
	HeadGroupID    string
	Mode           string
	Platforms      []string
}

func (q *Queries) ListDashboardChannelRuntimes(ctx context.Context, channel string) ([]ListDashboardChannelRuntimesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardChannelRuntimes, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardChannelRuntimesRow
	for rows.Next() {
		var i ListDashboardChannelRuntimesRow
		if err := rows.Scan(
			&i.RuntimeVersion,
			&i.UpdatedAt,
			&i.Version,
			&i.HeadGroupID,
			&i.Mode,
			&i.Platforms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardChannels = `-- name: ListDashboardChannels :many
SELECT channel, max(updated_at)::timestamptz AS updated_at, count(DISTINCT runtime_version) AS runtime_count FROM channel_heads GROUP BY channel ORDER BY channel
`

type ListDashboardChannelsRow struct {
	Channel      string
	UpdatedAt    pgtype.Timestamptz
	RuntimeCount int64
}

func (q *Queries) ListDashboardChannels(ctx context.Context) ([]ListDashboardChannelsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardChannelsRow
	for rows.Next() {
		var i ListDashboardChannelsRow
		if err := rows.Scan(&i.Channel, &i.UpdatedAt, &i.RuntimeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardRuntimeUpdates = `-- name: ListDashboardRuntimeUpdates :many
SELECT id,channel,runtime_version,COALESCE(expo_config->>'version','')::text AS app_version,message,created_at,source,fingerprint_hash FROM update_groups WHERE runtime_version=$1 ORDER BY created_at DESC
`

type ListDashboardRuntimeUpdatesRow struct {
	ID              pgtype.UUID
	Channel         string
	RuntimeVersion  string
	AppVersion      string
	Message         string
	CreatedAt       pgtype.Timestamptz
	Source          []byte
	FingerprintHash pgtype.Text
}

func (q *Queries) ListDashboardRuntimeUpdates(ctx context.Context, runtimeVersion string) ([]ListDashboardRuntimeUpdatesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardRuntimeUpdates, runtimeVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardRuntimeUpdatesRow
	for rows.Next() {
		var i ListDashboardRuntimeUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.AppVersion,
			&i.Message,
			&i.CreatedAt,
			&i.Source,
			&i.FingerprintHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardRuntimes = `-- name: ListDashboardRuntimes :many
SELECT runtime_version, (array_agg(COALESCE(expo_config->>'version','') ORDER BY created_at DESC))[1]::text AS version, max(created_at)::timestamptz AS updated_at, count(*)::bigint AS update_count, array_agg(DISTINCT channel ORDER BY channel)::text[] AS channels FROM update_groups GROUP BY runtime_version ORDER BY max(created_at) DESC
`

type ListDashboardRuntimesRow struct {
	RuntimeVersion string
	Version        string
	UpdatedAt      pgtype.Timestamptz
	UpdateCount    int64
	Channels       []string
}

func (q *Queries) ListDashboardRuntimes(ctx context.Context) ([]ListDashboardRuntimesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardRuntimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardRuntimesRow
	for rows.Next() {
		var i ListDashboardRuntimesRow
		if err := rows.Scan(
			&i.RuntimeVersion,
			&i.Version,
			&i.UpdatedAt,
			&i.UpdateCount,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUpdateAssets = `-- name: ListDashboardUpdateAssets :many
SELECT a.id,a.asset_key,a.content_type,a.size_bytes,a.is_launch FROM updates u JOIN assets a ON a.update_id=u.id WHERE u.group_id=$1 AND u.platform=$2 ORDER BY a.is_launch DESC,a.size_bytes DESC
`

type ListDashboardUpdateAssetsParams struct {
	GroupID  pgtype.UUID
	Platform string
}

type ListDashboardUpdateAssetsRow struct {
	ID          int64
	AssetKey    string
	ContentType string
	SizeBytes   int64
	IsLaunch    bool
}

func (q *Queries) ListDashboardUpdateAssets(ctx context.Context, arg ListDashboardUpdateAssetsParams) ([]ListDashboardUpdateAssetsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUpdateAssets, arg.GroupID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardUpdateAssetsRow
	for rows.Next() {
		var i ListDashboardUpdateAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.IsLaunch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUpdatePatches = `-- name: ListDashboardUpdatePatches :many
SELECT p.id,p.to_update_id,p.from_update_id,p.platform,p.status,p.size_bytes,p.attempts,p.error,p.updated_at,fu.group_id AS from_group_id,fug.message AS from_message
FROM patches p
JOIN updates tu ON tu.id=p.to_update_id
JOIN updates fu ON fu.id=p.from_update_id
JOIN update_groups fug ON fug.id=fu.group_id
WHERE tu.group_id=$1
ORDER BY p.platform,p.created_at DESC
`

type ListDashboardUpdatePatchesRow struct {
	ID           int64
	ToUpdateID   pgtype.UUID
	FromUpdateID pgtype.UUID
	Platform     string
	Status       string
	SizeBytes    pgtype.Int8
	Attempts     int32
	Error        pgtype.Text
	UpdatedAt    pgtype.Timestamptz
	FromGroupID  pgtype.UUID
	FromMessage  string
}

func (q *Queries) ListDashboardUpdatePatches(ctx context.Context, groupID pgtype.UUID) ([]ListDashboardUpdatePatchesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUpdatePatches, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardUpdatePatchesRow
	for rows.Next() {
		var i ListDashboardUpdatePatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ToUpdateID,
			&i.FromUpdateID,
			&i.Platform,
			&i.Status,
			&i.SizeBytes,
			&i.Attempts,
			&i.Error,
			&i.UpdatedAt,
			&i.FromGroupID,
			&i.FromMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUpdatePlatforms = `-- name: ListDashboardUpdatePlatforms :many
SELECT u.id,u.platform,u.launch_key,u.launch_hash,a.size_bytes,COALESCE((SELECT sum(m.request_count) FILTER (WHERE m.kind='launch_bundle') FROM delivery_metric_minutes m WHERE m.group_id=u.group_id AND m.platform=u.platform AND m.outcome='served'),0)::bigint AS full_downloads,COALESCE((SELECT sum(m.request_count) FILTER (WHERE m.kind='patch') FROM delivery_metric_minutes m WHERE m.group_id=u.group_id AND m.platform=u.platform AND m.outcome='served'),0)::bigint AS patch_downloads,(SELECT count(*) FROM known_update_launches l WHERE l.group_id=u.group_id AND l.platform=u.platform) AS known_launches,(SELECT count(*) FROM known_update_crashes c WHERE c.group_id=u.group_id AND c.platform=u.platform) AS known_crashes FROM updates u JOIN assets a ON a.update_id=u.id AND a.is_launch WHERE u.group_id=$1 ORDER BY u.platform
`

type ListDashboardUpdatePlatformsRow struct {
	ID             pgtype.UUID
	Platform       string
	LaunchKey      string
	LaunchHash     string
	SizeBytes      int64
	FullDownloads  int64
	PatchDownloads int64
	KnownLaunches  int64
	KnownCrashes   int64
}

func (q *Queries) ListDashboardUpdatePlatforms(ctx context.Context, groupID pgtype.UUID) ([]ListDashboardUpdatePlatformsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUpdatePlatforms, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardUpdatePlatformsRow
	for rows.Next() {
		var i ListDashboardUpdatePlatformsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.LaunchKey,
			&i.LaunchHash,
			&i.SizeBytes,
			&i.FullDownloads,
			&i.PatchDownloads,
			&i.KnownLaunches,
			&i.KnownCrashes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
