// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventInsightSummary = `-- name: GetEventInsightSummary :one
SELECT count(DISTINCT installation_hmac) AS unique_users,count(*) FILTER (WHERE event_type='launch_succeeded') AS launch_successes,count(*) FILTER (WHERE event_type='launch_failed') AS launch_failures
FROM update_events
WHERE occurred_at >= now()-interval '7 days'
  AND ($1::text IS NULL OR channel=$1::text)
  AND ($2::text IS NULL OR runtime_version=$2::text)
  AND ($3::text IS NULL OR platform=$3::text)
  AND ($4::uuid IS NULL OR group_id=$4::uuid)
`

type GetEventInsightSummaryParams struct {
	Channel        pgtype.Text
	RuntimeVersion pgtype.Text
	Platform       pgtype.Text
	GroupID        pgtype.UUID
}

type GetEventInsightSummaryRow struct {
	UniqueUsers     int64
	LaunchSuccesses int64
	LaunchFailures  int64
}

func (q *Queries) GetEventInsightSummary(ctx context.Context, arg GetEventInsightSummaryParams) (GetEventInsightSummaryRow, error) {
	row := q.db.QueryRow(ctx, getEventInsightSummary,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
	)
	var i GetEventInsightSummaryRow
	err := row.Scan(&i.UniqueUsers, &i.LaunchSuccesses, &i.LaunchFailures)
	return i, err
}

const insertClientEvent = `-- name: InsertClientEvent :exec
INSERT INTO update_events(id,schema_version,event_type,occurred_at,installation_hmac,client_version,client_build_version,expo_updates_version,updates_protocol_version,platform,runtime_version,channel,update_id,embedded_update_id,group_id,launch_source,payload)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT(id) DO NOTHING
`

type InsertClientEventParams struct {
	ID                     pgtype.UUID
	SchemaVersion          int32
	EventType              string
	OccurredAt             pgtype.Timestamptz
	InstallationHmac       pgtype.Text
	ClientVersion          pgtype.Text
	ClientBuildVersion     pgtype.Text
	ExpoUpdatesVersion     pgtype.Text
	UpdatesProtocolVersion pgtype.Text
	Platform               pgtype.Text
	RuntimeVersion         pgtype.Text
	Channel                pgtype.Text
	UpdateID               pgtype.UUID
	EmbeddedUpdateID       pgtype.UUID
	GroupID                pgtype.UUID
	LaunchSource           pgtype.Text
	Payload                []byte
}

func (q *Queries) InsertClientEvent(ctx context.Context, arg InsertClientEventParams) error {
	_, err := q.db.Exec(ctx, insertClientEvent,
		arg.ID,
		arg.SchemaVersion,
		arg.EventType,
		arg.OccurredAt,
		arg.InstallationHmac,
		arg.ClientVersion,
		arg.ClientBuildVersion,
		arg.ExpoUpdatesVersion,
		arg.UpdatesProtocolVersion,
		arg.Platform,
		arg.RuntimeVersion,
		arg.Channel,
		arg.UpdateID,
		arg.EmbeddedUpdateID,
		arg.GroupID,
		arg.LaunchSource,
		arg.Payload,
	)
	return err
}
