// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByID = `-- name: CountEventsByID :one
SELECT count(*) AS event_count FROM update_events WHERE id=$1
`

func (q *Queries) CountEventsByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByID, id)
	var event_count int64
	err := row.Scan(&event_count)
	return event_count, err
}

const getEventInsightSummary = `-- name: GetEventInsightSummary :one
SELECT count(DISTINCT installation_hmac) AS unique_installations,count(*) FILTER (WHERE event_type LIKE 'update_check%') AS update_checks,count(*) FILTER (WHERE event_type LIKE 'download%') AS downloads,count(*) FILTER (WHERE event_type='launch_started') AS launches,count(*) FILTER (WHERE event_type='launch_succeeded') AS launch_successes,count(*) FILTER (WHERE event_type IN ('launch_failed','error_recovery')) AS launch_failures,count(*) FILTER (WHERE event_type='emergency_launch') AS emergency_launches
FROM update_events
WHERE occurred_at >= now()-interval '7 days'
  AND ($1::text IS NULL OR channel=$1::text)
  AND ($2::text IS NULL OR runtime_version=$2::text)
  AND ($3::text IS NULL OR platform=$3::text)
  AND ($4::uuid IS NULL OR group_id=$4::uuid)
`

type GetEventInsightSummaryParams struct {
	Channel        pgtype.Text
	RuntimeVersion pgtype.Text
	Platform       pgtype.Text
	GroupID        pgtype.UUID
}

type GetEventInsightSummaryRow struct {
	UniqueInstallations int64
	UpdateChecks        int64
	Downloads           int64
	Launches            int64
	LaunchSuccesses     int64
	LaunchFailures      int64
	EmergencyLaunches   int64
}

func (q *Queries) GetEventInsightSummary(ctx context.Context, arg GetEventInsightSummaryParams) (GetEventInsightSummaryRow, error) {
	row := q.db.QueryRow(ctx, getEventInsightSummary,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
	)
	var i GetEventInsightSummaryRow
	err := row.Scan(
		&i.UniqueInstallations,
		&i.UpdateChecks,
		&i.Downloads,
		&i.Launches,
		&i.LaunchSuccesses,
		&i.LaunchFailures,
		&i.EmergencyLaunches,
	)
	return i, err
}

const insertClientEvent = `-- name: InsertClientEvent :exec
INSERT INTO update_events(id,schema_version,event_type,occurred_at,installation_hmac,client_version,client_build_version,expo_updates_version,updates_protocol_version,platform,runtime_version,channel,update_id,embedded_update_id,group_id,launch_source,payload)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT(id) DO NOTHING
`

type InsertClientEventParams struct {
	ID                     pgtype.UUID
	SchemaVersion          int32
	EventType              string
	OccurredAt             pgtype.Timestamptz
	InstallationHmac       pgtype.Text
	ClientVersion          pgtype.Text
	ClientBuildVersion     pgtype.Text
	ExpoUpdatesVersion     pgtype.Text
	UpdatesProtocolVersion pgtype.Text
	Platform               pgtype.Text
	RuntimeVersion         pgtype.Text
	Channel                pgtype.Text
	UpdateID               pgtype.UUID
	EmbeddedUpdateID       pgtype.UUID
	GroupID                pgtype.UUID
	LaunchSource           pgtype.Text
	Payload                []byte
}

func (q *Queries) InsertClientEvent(ctx context.Context, arg InsertClientEventParams) error {
	_, err := q.db.Exec(ctx, insertClientEvent,
		arg.ID,
		arg.SchemaVersion,
		arg.EventType,
		arg.OccurredAt,
		arg.InstallationHmac,
		arg.ClientVersion,
		arg.ClientBuildVersion,
		arg.ExpoUpdatesVersion,
		arg.UpdatesProtocolVersion,
		arg.Platform,
		arg.RuntimeVersion,
		arg.Channel,
		arg.UpdateID,
		arg.EmbeddedUpdateID,
		arg.GroupID,
		arg.LaunchSource,
		arg.Payload,
	)
	return err
}

const insertServerEvent = `-- name: InsertServerEvent :exec
INSERT INTO update_events(id,schema_version,event_type,occurred_at,platform,runtime_version,channel,group_id,payload)
VALUES(gen_random_uuid(),1,$1,now(),$2,$3,$4,$5,$6)
`

type InsertServerEventParams struct {
	EventType      string
	Platform       pgtype.Text
	RuntimeVersion pgtype.Text
	Channel        pgtype.Text
	GroupID        pgtype.UUID
	Payload        []byte
}

func (q *Queries) InsertServerEvent(ctx context.Context, arg InsertServerEventParams) error {
	_, err := q.db.Exec(ctx, insertServerEvent,
		arg.EventType,
		arg.Platform,
		arg.RuntimeVersion,
		arg.Channel,
		arg.GroupID,
		arg.Payload,
	)
	return err
}

const listEventInsights = `-- name: ListEventInsights :many
SELECT event_type,count(*) AS event_count,count(DISTINCT installation_hmac) AS unique_installations
FROM update_events
WHERE occurred_at >= now()-interval '7 days'
  AND ($1::text IS NULL OR channel=$1::text)
  AND ($2::text IS NULL OR runtime_version=$2::text)
  AND ($3::text IS NULL OR platform=$3::text)
  AND ($4::uuid IS NULL OR group_id=$4::uuid)
GROUP BY event_type ORDER BY event_type
`

type ListEventInsightsParams struct {
	Channel        pgtype.Text
	RuntimeVersion pgtype.Text
	Platform       pgtype.Text
	GroupID        pgtype.UUID
}

type ListEventInsightsRow struct {
	EventType           string
	EventCount          int64
	UniqueInstallations int64
}

func (q *Queries) ListEventInsights(ctx context.Context, arg ListEventInsightsParams) ([]ListEventInsightsRow, error) {
	rows, err := q.db.Query(ctx, listEventInsights,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventInsightsRow
	for rows.Next() {
		var i ListEventInsightsRow
		if err := rows.Scan(&i.EventType, &i.EventCount, &i.UniqueInstallations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
