// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredDeliveryMetrics = `-- name: DeleteExpiredDeliveryMetrics :exec
DELETE FROM delivery_metric_minutes WHERE minute < now()-interval '90 days'
`

func (q *Queries) DeleteExpiredDeliveryMetrics(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredDeliveryMetrics)
	return err
}

const deleteExpiredRawEvents = `-- name: DeleteExpiredRawEvents :exec
DELETE FROM update_events WHERE created_at < now()-interval '35 days'
`

func (q *Queries) DeleteExpiredRawEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRawEvents)
	return err
}

const deleteExpiredServiceMetrics = `-- name: DeleteExpiredServiceMetrics :exec
DELETE FROM service_metric_minutes WHERE minute < now()-interval '90 days'
`

func (q *Queries) DeleteExpiredServiceMetrics(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredServiceMetrics)
	return err
}

const getDeliveryMetricSeries = `-- name: GetDeliveryMetricSeries :many
SELECT minute::date AS day,
       kind,
       outcome,
       sum(request_count)::bigint AS request_count,
       sum(byte_count)::bigint AS byte_count,
       sum(target_byte_count)::bigint AS target_byte_count
FROM delivery_metric_minutes
WHERE minute >= $1 AND minute < $2
  AND ($3::text IS NULL OR channel=$3::text)
  AND ($4::text IS NULL OR runtime_version=$4::text)
  AND ($5::text IS NULL OR platform=$5::text)
  AND ($6::uuid IS NULL OR group_id=$6::uuid)
GROUP BY day,kind,outcome
ORDER BY day,kind,outcome
`

type GetDeliveryMetricSeriesParams struct {
	Minute         pgtype.Timestamptz
	Minute_2       pgtype.Timestamptz
	Channel        pgtype.Text
	RuntimeVersion pgtype.Text
	Platform       pgtype.Text
	GroupID        pgtype.UUID
}

type GetDeliveryMetricSeriesRow struct {
	Day             pgtype.Date
	Kind            string
	Outcome         string
	RequestCount    int64
	ByteCount       int64
	TargetByteCount int64
}

func (q *Queries) GetDeliveryMetricSeries(ctx context.Context, arg GetDeliveryMetricSeriesParams) ([]GetDeliveryMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, getDeliveryMetricSeries,
		arg.Minute,
		arg.Minute_2,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeliveryMetricSeriesRow
	for rows.Next() {
		var i GetDeliveryMetricSeriesRow
		if err := rows.Scan(
			&i.Day,
			&i.Kind,
			&i.Outcome,
			&i.RequestCount,
			&i.ByteCount,
			&i.TargetByteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceMetricSeries = `-- name: GetServiceMetricSeries :many
SELECT minute,
       sum(request_count)::bigint AS request_count,
       COALESCE(sum(request_count) FILTER (WHERE status >= 500), 0)::bigint AS error_count,
       COALESCE(sum(duration_ms), 0)::bigint AS duration_ms
FROM service_metric_minutes
WHERE minute >= $1 AND minute < $2
  AND ($3::text IS NULL OR route=$3::text)
GROUP BY minute
ORDER BY minute
`

type GetServiceMetricSeriesParams struct {
	Minute   pgtype.Timestamptz
	Minute_2 pgtype.Timestamptz
	Route    pgtype.Text
}

type GetServiceMetricSeriesRow struct {
	Minute       pgtype.Timestamptz
	RequestCount int64
	ErrorCount   int64
	DurationMs   int64
}

func (q *Queries) GetServiceMetricSeries(ctx context.Context, arg GetServiceMetricSeriesParams) ([]GetServiceMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, getServiceMetricSeries, arg.Minute, arg.Minute_2, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServiceMetricSeriesRow
	for rows.Next() {
		var i GetServiceMetricSeriesRow
		if err := rows.Scan(
			&i.Minute,
			&i.RequestCount,
			&i.ErrorCount,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransportInsightSummary = `-- name: GetTransportInsightSummary :one
SELECT COALESCE(sum(request_count) FILTER (WHERE kind='patch' AND outcome='served'),0)::bigint AS patch_requests,
       COALESCE(sum(request_count) FILTER (WHERE kind='patch_fallback'),0)::bigint AS patch_fallbacks,
       COALESCE(sum(request_count) FILTER (WHERE kind='launch_bundle' AND outcome='served'),0)::bigint AS full_requests,
       COALESCE(sum(byte_count) FILTER (WHERE kind='patch' AND outcome='served'),0)::bigint AS patch_bytes,
       COALESCE(sum(target_byte_count) FILTER (WHERE kind='patch' AND outcome='served'),0)::bigint AS patch_target_bytes,
       COALESCE(sum(byte_count) FILTER (WHERE kind='launch_bundle' AND outcome='served'),0)::bigint AS full_bytes
FROM delivery_metric_minutes
WHERE minute >= now()-interval '7 days'
  AND ($1::text IS NULL OR channel=$1::text)
  AND ($2::text IS NULL OR runtime_version=$2::text)
  AND ($3::text IS NULL OR platform=$3::text)
  AND ($4::uuid IS NULL OR group_id=$4::uuid)
`

type GetTransportInsightSummaryParams struct {
	Channel        pgtype.Text
	RuntimeVersion pgtype.Text
	Platform       pgtype.Text
	GroupID        pgtype.UUID
}

type GetTransportInsightSummaryRow struct {
	PatchRequests    int64
	PatchFallbacks   int64
	FullRequests     int64
	PatchBytes       int64
	PatchTargetBytes int64
	FullBytes        int64
}

func (q *Queries) GetTransportInsightSummary(ctx context.Context, arg GetTransportInsightSummaryParams) (GetTransportInsightSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTransportInsightSummary,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
	)
	var i GetTransportInsightSummaryRow
	err := row.Scan(
		&i.PatchRequests,
		&i.PatchFallbacks,
		&i.FullRequests,
		&i.PatchBytes,
		&i.PatchTargetBytes,
		&i.FullBytes,
	)
	return i, err
}

const getUpdateGroupLifecycleSeries = `-- name: GetUpdateGroupLifecycleSeries :many
SELECT day, sum(known_launches)::bigint AS known_launches, sum(known_crashes)::bigint AS known_crashes
FROM (
  SELECT confirmed_at::date AS day, count(*)::bigint AS known_launches, 0::bigint AS known_crashes
  FROM known_update_launches
  WHERE known_update_launches.group_id=$1 AND known_update_launches.confirmed_at >= $2 AND known_update_launches.confirmed_at < $3
  GROUP BY 1
  UNION ALL
  SELECT confirmed_at::date AS day, 0::bigint AS known_launches, count(*)::bigint AS known_crashes
  FROM known_update_crashes
  WHERE known_update_crashes.group_id=$1 AND known_update_crashes.confirmed_at >= $2 AND known_update_crashes.confirmed_at < $3
  GROUP BY 1
) lifecycle
GROUP BY day
ORDER BY day
`

type GetUpdateGroupLifecycleSeriesParams struct {
	GroupID       pgtype.UUID
	ConfirmedAt   pgtype.Timestamptz
	ConfirmedAt_2 pgtype.Timestamptz
}

type GetUpdateGroupLifecycleSeriesRow struct {
	Day           pgtype.Date
	KnownLaunches int64
	KnownCrashes  int64
}

func (q *Queries) GetUpdateGroupLifecycleSeries(ctx context.Context, arg GetUpdateGroupLifecycleSeriesParams) ([]GetUpdateGroupLifecycleSeriesRow, error) {
	rows, err := q.db.Query(ctx, getUpdateGroupLifecycleSeries, arg.GroupID, arg.ConfirmedAt, arg.ConfirmedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateGroupLifecycleSeriesRow
	for rows.Next() {
		var i GetUpdateGroupLifecycleSeriesRow
		if err := rows.Scan(&i.Day, &i.KnownLaunches, &i.KnownCrashes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDeliveryMetric = `-- name: RecordDeliveryMetric :exec
INSERT INTO delivery_metric_minutes(minute,channel,runtime_version,platform,group_id,kind,outcome,request_count,byte_count,target_byte_count)
VALUES(date_trunc('minute', now()), $1, $2, $3, $4, $5, $6, 1, $7, $8)
ON CONFLICT(minute,channel,runtime_version,platform,group_id,kind,outcome) DO UPDATE
SET request_count=delivery_metric_minutes.request_count+1,
    byte_count=delivery_metric_minutes.byte_count+excluded.byte_count,
    target_byte_count=delivery_metric_minutes.target_byte_count+excluded.target_byte_count
`

type RecordDeliveryMetricParams struct {
	Channel         string
	RuntimeVersion  string
	Platform        string
	GroupID         pgtype.UUID
	Kind            string
	Outcome         string
	ByteCount       int64
	TargetByteCount int64
}

func (q *Queries) RecordDeliveryMetric(ctx context.Context, arg RecordDeliveryMetricParams) error {
	_, err := q.db.Exec(ctx, recordDeliveryMetric,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.GroupID,
		arg.Kind,
		arg.Outcome,
		arg.ByteCount,
		arg.TargetByteCount,
	)
	return err
}

const recordInstallationActivity = `-- name: RecordInstallationActivity :exec
INSERT INTO installation_activity_days(day,installation_hmac,channel,runtime_version,platform,client_version,client_build_version,update_id,group_id,first_seen_at,last_seen_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)
ON CONFLICT(day,installation_hmac,channel,runtime_version,platform,client_version,client_build_version,update_id) DO UPDATE
SET last_seen_at=GREATEST(installation_activity_days.last_seen_at, excluded.last_seen_at),
    group_id=COALESCE(excluded.group_id, installation_activity_days.group_id)
`

type RecordInstallationActivityParams struct {
	Day                pgtype.Date
	InstallationHmac   string
	Channel            string
	RuntimeVersion     string
	Platform           string
	ClientVersion      string
	ClientBuildVersion string
	UpdateID           pgtype.UUID
	GroupID            pgtype.UUID
	FirstSeenAt        pgtype.Timestamptz
}

func (q *Queries) RecordInstallationActivity(ctx context.Context, arg RecordInstallationActivityParams) error {
	_, err := q.db.Exec(ctx, recordInstallationActivity,
		arg.Day,
		arg.InstallationHmac,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.ClientVersion,
		arg.ClientBuildVersion,
		arg.UpdateID,
		arg.GroupID,
		arg.FirstSeenAt,
	)
	return err
}

const recordKnownCrash = `-- name: RecordKnownCrash :exec
INSERT INTO known_update_crashes(installation_hmac,update_id,group_id,channel,runtime_version,platform,confirmed_at)
VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(installation_hmac,update_id) DO NOTHING
`

type RecordKnownCrashParams struct {
	InstallationHmac string
	UpdateID         pgtype.UUID
	GroupID          pgtype.UUID
	Channel          string
	RuntimeVersion   string
	Platform         string
	ConfirmedAt      pgtype.Timestamptz
}

func (q *Queries) RecordKnownCrash(ctx context.Context, arg RecordKnownCrashParams) error {
	_, err := q.db.Exec(ctx, recordKnownCrash,
		arg.InstallationHmac,
		arg.UpdateID,
		arg.GroupID,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.ConfirmedAt,
	)
	return err
}

const recordKnownLaunch = `-- name: RecordKnownLaunch :exec
INSERT INTO known_update_launches(installation_hmac,update_id,group_id,channel,runtime_version,platform,confirmed_at)
VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(installation_hmac,update_id) DO NOTHING
`

type RecordKnownLaunchParams struct {
	InstallationHmac string
	UpdateID         pgtype.UUID
	GroupID          pgtype.UUID
	Channel          string
	RuntimeVersion   string
	Platform         string
	ConfirmedAt      pgtype.Timestamptz
}

func (q *Queries) RecordKnownLaunch(ctx context.Context, arg RecordKnownLaunchParams) error {
	_, err := q.db.Exec(ctx, recordKnownLaunch,
		arg.InstallationHmac,
		arg.UpdateID,
		arg.GroupID,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Platform,
		arg.ConfirmedAt,
	)
	return err
}

const recordServiceMetric = `-- name: RecordServiceMetric :exec
INSERT INTO service_metric_minutes(minute,route,status,request_count,duration_ms)
VALUES(date_trunc('minute', now()), $1, $2, 1, $3)
ON CONFLICT(minute,route,status) DO UPDATE
SET request_count=service_metric_minutes.request_count+1,
    duration_ms=service_metric_minutes.duration_ms+excluded.duration_ms
`

type RecordServiceMetricParams struct {
	Route      string
	Status     int32
	DurationMs int64
}

func (q *Queries) RecordServiceMetric(ctx context.Context, arg RecordServiceMetricParams) error {
	_, err := q.db.Exec(ctx, recordServiceMetric, arg.Route, arg.Status, arg.DurationMs)
	return err
}
