// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID          int64
	UpdateID    pgtype.UUID
	AssetKey    string
	ObjectKey   string
	Sha256      string
	ContentType string
	SizeBytes   int64
	IsLaunch    bool
}

type ChannelHead struct {
	Channel        string
	RuntimeVersion string
	Platform       string
	GroupID        pgtype.UUID
	Mode           string
	UpdatedAt      pgtype.Timestamptz
}

type ChannelHistory struct {
	ID             int64
	Channel        string
	RuntimeVersion string
	Platform       string
	GroupID        pgtype.UUID
	Mode           string
	Action         string
	Actor          pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type DailyUpdateMetric struct {
	Day                 pgtype.Date
	Channel             string
	RuntimeVersion      string
	Platform            string
	GroupID             pgtype.UUID
	EventType           string
	EventCount          int64
	UniqueInstallations int64
}

type Patch struct {
	ID                  int64
	FromUpdateID        pgtype.UUID
	ToUpdateID          pgtype.UUID
	Platform            string
	Status              string
	ObjectKey           pgtype.Text
	Sha256              pgtype.Text
	SizeBytes           pgtype.Int8
	Attempts            int32
	ServedCount         int64
	Error               pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ProcessingStartedAt pgtype.Timestamptz
}

type SourceCommit struct {
	UpdateGroupID pgtype.UUID
	Ordinal       int32
	CommitSha     string
	ParentSha     pgtype.Text
	Subject       string
	AuthorName    pgtype.Text
	AuthoredAt    pgtype.Timestamptz
}

type Update struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	Platform   string
	LaunchKey  string
	LaunchHash string
	CreatedAt  pgtype.Timestamptz
}

type UpdateEvent struct {
	ID                     pgtype.UUID
	SchemaVersion          int32
	EventType              string
	OccurredAt             pgtype.Timestamptz
	InstallationHmac       pgtype.Text
	ClientVersion          pgtype.Text
	ClientBuildVersion     pgtype.Text
	ExpoUpdatesVersion     pgtype.Text
	UpdatesProtocolVersion pgtype.Text
	Platform               pgtype.Text
	RuntimeVersion         pgtype.Text
	Channel                pgtype.Text
	UpdateID               pgtype.UUID
	EmbeddedUpdateID       pgtype.UUID
	GroupID                pgtype.UUID
	LaunchSource           pgtype.Text
	Payload                []byte
	CreatedAt              pgtype.Timestamptz
}

type UpdateGroup struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Message        string
	CreatedAt      pgtype.Timestamptz
	Source         []byte
	ExpoConfig     []byte
	MetadataSha256 string
	Status         string
}
