// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPatch = `-- name: ClaimPatch :one
WITH claimed AS (SELECT p.id,p.from_update_id,p.to_update_id,a1.object_key AS from_key,a2.object_key AS to_key,a2.size_bytes FROM patches p JOIN assets a1 ON a1.update_id=p.from_update_id AND a1.is_launch JOIN assets a2 ON a2.update_id=p.to_update_id AND a2.is_launch WHERE p.status='pending' OR (p.status='processing' AND p.processing_started_at < now()-interval '10 minutes') ORDER BY p.created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE patches p SET status='processing',attempts=p.attempts+1,processing_started_at=now(),updated_at=now() FROM claimed c WHERE p.id=c.id RETURNING c.id,c.from_update_id,c.to_update_id,c.from_key,c.to_key,c.size_bytes
`

type ClaimPatchRow struct {
	ID           int64
	FromUpdateID pgtype.UUID
	ToUpdateID   pgtype.UUID
	FromKey      string
	ToKey        string
	SizeBytes    int64
}

func (q *Queries) ClaimPatch(ctx context.Context) (ClaimPatchRow, error) {
	row := q.db.QueryRow(ctx, claimPatch)
	var i ClaimPatchRow
	err := row.Scan(
		&i.ID,
		&i.FromUpdateID,
		&i.ToUpdateID,
		&i.FromKey,
		&i.ToKey,
		&i.SizeBytes,
	)
	return i, err
}

const completePatch = `-- name: CompletePatch :exec
UPDATE patches SET status='ready',object_key=$2,sha256=$3,size_bytes=$4,error=NULL,processing_started_at=NULL,updated_at=now() WHERE id=$1
`

type CompletePatchParams struct {
	ID        int64
	ObjectKey pgtype.Text
	Sha256    pgtype.Text
	SizeBytes pgtype.Int8
}

func (q *Queries) CompletePatch(ctx context.Context, arg CompletePatchParams) error {
	_, err := q.db.Exec(ctx, completePatch,
		arg.ID,
		arg.ObjectKey,
		arg.Sha256,
		arg.SizeBytes,
	)
	return err
}

const failPatch = `-- name: FailPatch :exec
UPDATE patches SET status=$2,error=$3,processing_started_at=NULL,updated_at=now() WHERE id=$1
`

type FailPatchParams struct {
	ID     int64
	Status string
	Error  pgtype.Text
}

func (q *Queries) FailPatch(ctx context.Context, arg FailPatchParams) error {
	_, err := q.db.Exec(ctx, failPatch, arg.ID, arg.Status, arg.Error)
	return err
}

const getReadyPatchObjectKey = `-- name: GetReadyPatchObjectKey :one
SELECT object_key FROM patches WHERE from_update_id=$1 AND to_update_id=$2 AND status='ready'
`

type GetReadyPatchObjectKeyParams struct {
	FromUpdateID pgtype.UUID
	ToUpdateID   pgtype.UUID
}

func (q *Queries) GetReadyPatchObjectKey(ctx context.Context, arg GetReadyPatchObjectKeyParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getReadyPatchObjectKey, arg.FromUpdateID, arg.ToUpdateID)
	var object_key pgtype.Text
	err := row.Scan(&object_key)
	return object_key, err
}

const incrementPatchServed = `-- name: IncrementPatchServed :exec
UPDATE patches SET served_count=served_count+1 WHERE from_update_id=$1 AND to_update_id=$2
`

type IncrementPatchServedParams struct {
	FromUpdateID pgtype.UUID
	ToUpdateID   pgtype.UUID
}

func (q *Queries) IncrementPatchServed(ctx context.Context, arg IncrementPatchServedParams) error {
	_, err := q.db.Exec(ctx, incrementPatchServed, arg.FromUpdateID, arg.ToUpdateID)
	return err
}
