// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPendingPatch = `-- name: InsertPendingPatch :exec
INSERT INTO patches(from_update_id,to_update_id,platform,status) VALUES($1,$2,$3,'pending') ON CONFLICT(from_update_id,to_update_id) DO NOTHING
`

type InsertPendingPatchParams struct {
	FromUpdateID pgtype.UUID
	ToUpdateID   pgtype.UUID
	Platform     string
}

func (q *Queries) InsertPendingPatch(ctx context.Context, arg InsertPendingPatchParams) error {
	_, err := q.db.Exec(ctx, insertPendingPatch, arg.FromUpdateID, arg.ToUpdateID, arg.Platform)
	return err
}

const insertUpdate = `-- name: InsertUpdate :exec
INSERT INTO updates(id,group_id,platform,launch_key,launch_hash) VALUES($1,$2,$3,$4,$5)
`

type InsertUpdateParams struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	Platform   string
	LaunchKey  string
	LaunchHash string
}

func (q *Queries) InsertUpdate(ctx context.Context, arg InsertUpdateParams) error {
	_, err := q.db.Exec(ctx, insertUpdate,
		arg.ID,
		arg.GroupID,
		arg.Platform,
		arg.LaunchKey,
		arg.LaunchHash,
	)
	return err
}

const insertUpdateGroup = `-- name: InsertUpdateGroup :exec
INSERT INTO update_groups(id,channel,runtime_version,message,source,fingerprint_hash,fingerprint_sources,expo_config,metadata_sha256) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertUpdateGroupParams struct {
	ID                 pgtype.UUID
	Channel            string
	RuntimeVersion     string
	Message            string
	Source             []byte
	FingerprintHash    pgtype.Text
	FingerprintSources []byte
	ExpoConfig         []byte
	MetadataSha256     string
}

func (q *Queries) InsertUpdateGroup(ctx context.Context, arg InsertUpdateGroupParams) error {
	_, err := q.db.Exec(ctx, insertUpdateGroup,
		arg.ID,
		arg.Channel,
		arg.RuntimeVersion,
		arg.Message,
		arg.Source,
		arg.FingerprintHash,
		arg.FingerprintSources,
		arg.ExpoConfig,
		arg.MetadataSha256,
	)
	return err
}
