// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_commits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSourceCommit = `-- name: InsertSourceCommit :exec
INSERT INTO source_commits (update_group_id,ordinal,commit_sha,parent_sha,subject,author_name,authored_at) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type InsertSourceCommitParams struct {
	UpdateGroupID pgtype.UUID
	Ordinal       int32
	CommitSha     string
	ParentSha     pgtype.Text
	Subject       string
	AuthorName    pgtype.Text
	AuthoredAt    pgtype.Timestamptz
}

func (q *Queries) InsertSourceCommit(ctx context.Context, arg InsertSourceCommitParams) error {
	_, err := q.db.Exec(ctx, insertSourceCommit,
		arg.UpdateGroupID,
		arg.Ordinal,
		arg.CommitSha,
		arg.ParentSha,
		arg.Subject,
		arg.AuthorName,
		arg.AuthoredAt,
	)
	return err
}

const listSourceCommits = `-- name: ListSourceCommits :many
SELECT ordinal,commit_sha,parent_sha,subject,author_name,authored_at FROM source_commits WHERE update_group_id=$1 ORDER BY ordinal
`

type ListSourceCommitsRow struct {
	Ordinal    int32
	CommitSha  string
	ParentSha  pgtype.Text
	Subject    string
	AuthorName pgtype.Text
	AuthoredAt pgtype.Timestamptz
}

func (q *Queries) ListSourceCommits(ctx context.Context, updateGroupID pgtype.UUID) ([]ListSourceCommitsRow, error) {
	rows, err := q.db.Query(ctx, listSourceCommits, updateGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceCommitsRow
	for rows.Next() {
		var i ListSourceCommitsRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.CommitSha,
			&i.ParentSha,
			&i.Subject,
			&i.AuthorName,
			&i.AuthoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceCommitsForGroups = `-- name: ListSourceCommitsForGroups :many
SELECT update_group_id,ordinal,commit_sha,parent_sha,subject,author_name,authored_at FROM source_commits WHERE update_group_id=$1 OR update_group_id=$2 ORDER BY update_group_id,ordinal
`

type ListSourceCommitsForGroupsParams struct {
	UpdateGroupID   pgtype.UUID
	UpdateGroupID_2 pgtype.UUID
}

func (q *Queries) ListSourceCommitsForGroups(ctx context.Context, arg ListSourceCommitsForGroupsParams) ([]SourceCommit, error) {
	rows, err := q.db.Query(ctx, listSourceCommitsForGroups, arg.UpdateGroupID, arg.UpdateGroupID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceCommit
	for rows.Next() {
		var i SourceCommit
		if err := rows.Scan(
			&i.UpdateGroupID,
			&i.Ordinal,
			&i.CommitSha,
			&i.ParentSha,
			&i.Subject,
			&i.AuthorName,
			&i.AuthoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
