// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findGroupsByCommit = `-- name: FindGroupsByCommit :many
SELECT id,channel,runtime_version,message,created_at FROM update_groups WHERE source->>'commit_sha'=$1::text ORDER BY created_at DESC
`

type FindGroupsByCommitRow struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Message        string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) FindGroupsByCommit(ctx context.Context, commitSha string) ([]FindGroupsByCommitRow, error) {
	rows, err := q.db.Query(ctx, findGroupsByCommit, commitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGroupsByCommitRow
	for rows.Next() {
		var i FindGroupsByCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGroupsOrSourceCommitsByCommit = `-- name: FindGroupsOrSourceCommitsByCommit :many
SELECT ug.id,ug.channel,ug.runtime_version,ug.message,ug.created_at FROM update_groups ug WHERE ug.source->>'commit_sha'=$1 OR EXISTS (SELECT 1 FROM source_commits sc WHERE sc.update_group_id=ug.id AND sc.commit_sha=$1) ORDER BY ug.created_at DESC
`

type FindGroupsOrSourceCommitsByCommitRow struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Message        string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) FindGroupsOrSourceCommitsByCommit(ctx context.Context, source []byte) ([]FindGroupsOrSourceCommitsByCommitRow, error) {
	rows, err := q.db.Query(ctx, findGroupsOrSourceCommitsByCommit, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGroupsOrSourceCommitsByCommitRow
	for rows.Next() {
		var i FindGroupsOrSourceCommitsByCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateGroup = `-- name: GetUpdateGroup :one
SELECT id,channel,runtime_version,message,created_at,source,fingerprint_hash,fingerprint_sources,expo_config,metadata_sha256,status,republished_from_update_id FROM update_groups WHERE id=$1
`

func (q *Queries) GetUpdateGroup(ctx context.Context, id pgtype.UUID) (UpdateGroup, error) {
	row := q.db.QueryRow(ctx, getUpdateGroup, id)
	var i UpdateGroup
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.RuntimeVersion,
		&i.Message,
		&i.CreatedAt,
		&i.Source,
		&i.FingerprintHash,
		&i.FingerprintSources,
		&i.ExpoConfig,
		&i.MetadataSha256,
		&i.Status,
		&i.RepublishedFromUpdateID,
	)
	return i, err
}

const getUpdateGroupArtifacts = `-- name: GetUpdateGroupArtifacts :one
SELECT metadata_sha256,expo_config FROM update_groups WHERE id=$1
`

type GetUpdateGroupArtifactsRow struct {
	MetadataSha256 string
	ExpoConfig     []byte
}

func (q *Queries) GetUpdateGroupArtifacts(ctx context.Context, id pgtype.UUID) (GetUpdateGroupArtifactsRow, error) {
	row := q.db.QueryRow(ctx, getUpdateGroupArtifacts, id)
	var i GetUpdateGroupArtifactsRow
	err := row.Scan(&i.MetadataSha256, &i.ExpoConfig)
	return i, err
}

const getUpdateGroupSource = `-- name: GetUpdateGroupSource :one
SELECT source FROM update_groups WHERE id=$1
`

func (q *Queries) GetUpdateGroupSource(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUpdateGroupSource, id)
	var source []byte
	err := row.Scan(&source)
	return source, err
}

const latestSourceCommit = `-- name: LatestSourceCommit :one
SELECT COALESCE(source->>'commit_sha', '')::text AS commit_sha FROM channel_heads h JOIN update_groups g ON g.id=h.group_id WHERE h.channel=$1 AND h.runtime_version=$2 AND h.mode='ota' ORDER BY h.updated_at DESC LIMIT 1
`

type LatestSourceCommitParams struct {
	Channel        string
	RuntimeVersion string
}

func (q *Queries) LatestSourceCommit(ctx context.Context, arg LatestSourceCommitParams) (string, error) {
	row := q.db.QueryRow(ctx, latestSourceCommit, arg.Channel, arg.RuntimeVersion)
	var commit_sha string
	err := row.Scan(&commit_sha)
	return commit_sha, err
}

const listUpdateGroups = `-- name: ListUpdateGroups :many
SELECT id,channel,runtime_version,COALESCE(expo_config->>'version','')::text AS app_version,message,created_at,source,fingerprint_hash,republished_from_update_id FROM update_groups ORDER BY created_at DESC LIMIT $2 OFFSET $1
`

type ListUpdateGroupsParams struct {
	Offset int32
	Limit  int32
}

type ListUpdateGroupsRow struct {
	ID                      pgtype.UUID
	Channel                 string
	RuntimeVersion          string
	AppVersion              string
	Message                 string
	CreatedAt               pgtype.Timestamptz
	Source                  []byte
	FingerprintHash         pgtype.Text
	RepublishedFromUpdateID pgtype.UUID
}

func (q *Queries) ListUpdateGroups(ctx context.Context, arg ListUpdateGroupsParams) ([]ListUpdateGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUpdateGroups, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpdateGroupsRow
	for rows.Next() {
		var i ListUpdateGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.AppVersion,
			&i.Message,
			&i.CreatedAt,
			&i.Source,
			&i.FingerprintHash,
			&i.RepublishedFromUpdateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdatesForGroup = `-- name: ListUpdatesForGroup :many
SELECT platform,launch_hash FROM updates WHERE group_id=$1 ORDER BY platform
`

type ListUpdatesForGroupRow struct {
	Platform   string
	LaunchHash string
}

func (q *Queries) ListUpdatesForGroup(ctx context.Context, groupID pgtype.UUID) ([]ListUpdatesForGroupRow, error) {
	rows, err := q.db.Query(ctx, listUpdatesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpdatesForGroupRow
	for rows.Next() {
		var i ListUpdatesForGroupRow
		if err := rows.Scan(&i.Platform, &i.LaunchHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
