// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findGroupsByCommit = `-- name: FindGroupsByCommit :many
SELECT id, channel, runtime_version, message, created_at
FROM update_groups
WHERE source->>'commit_sha' = $1::text
ORDER BY created_at DESC
`

type FindGroupsByCommitRow struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Message        string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) FindGroupsByCommit(ctx context.Context, commitSha string) ([]FindGroupsByCommitRow, error) {
	rows, err := q.db.Query(ctx, findGroupsByCommit, commitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGroupsByCommitRow
	for rows.Next() {
		var i FindGroupsByCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateGroup = `-- name: GetUpdateGroup :one
SELECT id, channel, runtime_version, message, created_at, source, expo_config, metadata_sha256, status
FROM update_groups
WHERE id = $1
`

func (q *Queries) GetUpdateGroup(ctx context.Context, id pgtype.UUID) (UpdateGroup, error) {
	row := q.db.QueryRow(ctx, getUpdateGroup, id)
	var i UpdateGroup
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.RuntimeVersion,
		&i.Message,
		&i.CreatedAt,
		&i.Source,
		&i.ExpoConfig,
		&i.MetadataSha256,
		&i.Status,
	)
	return i, err
}

const insertSourceCommit = `-- name: InsertSourceCommit :exec
INSERT INTO source_commits (update_group_id, ordinal, commit_sha, parent_sha, subject, author_name, authored_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSourceCommitParams struct {
	UpdateGroupID pgtype.UUID
	Ordinal       int32
	CommitSha     string
	ParentSha     pgtype.Text
	Subject       string
	AuthorName    pgtype.Text
	AuthoredAt    pgtype.Timestamptz
}

func (q *Queries) InsertSourceCommit(ctx context.Context, arg InsertSourceCommitParams) error {
	_, err := q.db.Exec(ctx, insertSourceCommit,
		arg.UpdateGroupID,
		arg.Ordinal,
		arg.CommitSha,
		arg.ParentSha,
		arg.Subject,
		arg.AuthorName,
		arg.AuthoredAt,
	)
	return err
}

const latestSourceCommit = `-- name: LatestSourceCommit :one
SELECT COALESCE(source->>'commit_sha', '')::text AS commit_sha
FROM channel_heads h
JOIN update_groups g ON g.id = h.group_id
WHERE h.channel = $1 AND h.runtime_version = $2 AND h.mode = 'ota'
ORDER BY h.updated_at DESC
LIMIT 1
`

type LatestSourceCommitParams struct {
	Channel        string
	RuntimeVersion string
}

func (q *Queries) LatestSourceCommit(ctx context.Context, arg LatestSourceCommitParams) (string, error) {
	row := q.db.QueryRow(ctx, latestSourceCommit, arg.Channel, arg.RuntimeVersion)
	var commit_sha string
	err := row.Scan(&commit_sha)
	return commit_sha, err
}

const listSourceCommits = `-- name: ListSourceCommits :many
SELECT ordinal, commit_sha, parent_sha, subject, author_name, authored_at
FROM source_commits
WHERE update_group_id = $1
ORDER BY ordinal
`

type ListSourceCommitsRow struct {
	Ordinal    int32
	CommitSha  string
	ParentSha  pgtype.Text
	Subject    string
	AuthorName pgtype.Text
	AuthoredAt pgtype.Timestamptz
}

func (q *Queries) ListSourceCommits(ctx context.Context, updateGroupID pgtype.UUID) ([]ListSourceCommitsRow, error) {
	rows, err := q.db.Query(ctx, listSourceCommits, updateGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceCommitsRow
	for rows.Next() {
		var i ListSourceCommitsRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.CommitSha,
			&i.ParentSha,
			&i.Subject,
			&i.AuthorName,
			&i.AuthoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdateGroups = `-- name: ListUpdateGroups :many
SELECT id, channel, runtime_version, message, created_at, source
FROM update_groups
ORDER BY created_at DESC
LIMIT $1
`

type ListUpdateGroupsRow struct {
	ID             pgtype.UUID
	Channel        string
	RuntimeVersion string
	Message        string
	CreatedAt      pgtype.Timestamptz
	Source         []byte
}

func (q *Queries) ListUpdateGroups(ctx context.Context, limit int32) ([]ListUpdateGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUpdateGroups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpdateGroupsRow
	for rows.Next() {
		var i ListUpdateGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.RuntimeVersion,
			&i.Message,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
