export const LIST_ITEM_COVER_SIZE = 48
export const LIST_ITEM_BORDER_RADIUS = 12

export const SQUIRCLE_RADIUS_RATIO = 0.22

export const SQUIRCLE_CORNER_SMOOTHING = 0.6

export const LIST_ITEM_HEIGHT = 64
