name: Build and Release

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: '构建类型'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev
          - preview
          - blank-test

  pull_request:
    types: [closed]
    branches:
      - master

env:
  NODE_VERSION: 22.x
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MENTION_USER: '@roitium'

jobs:
  setup:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      buildType: ${{ steps.set-vars.outputs.buildType }}
      profile: ${{ steps.set-matrix.outputs.profile }}
      commitSha: ${{ steps.set-vars.outputs.commitSha }}
      prNumber: ${{ steps.set-vars.outputs.prNumber }}
    steps:
      - name: Determine Variables
        id: set-vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "buildType=prod" >> $GITHUB_OUTPUT
            echo "commitSha=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_OUTPUT
            echo "prNumber=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "buildType=${{ github.event.inputs.buildType }}" >> $GITHUB_OUTPUT
            echo "commitSha=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "prNumber=" >> $GITHUB_OUTPUT
          fi

      - name: Determine Matrix and Profile
        id: set-matrix
        run: |
          BUILD_TYPE="${{ steps.set-vars.outputs.buildType }}"

          if [[ "$BUILD_TYPE" == "prod" ]]; then
            echo "matrix={\"include\":[{\"arch\":\"arm64-v8a\"},{\"arch\":\"armeabi-v7a\"},{\"arch\":\"x86_64\"},{\"arch\":\"x86\"}]}" >> $GITHUB_OUTPUT
            echo "profile=prod-ci" >> $GITHUB_OUTPUT
          elif [[ "$BUILD_TYPE" == "blank-test" ]]; then
             echo "matrix={\"include\":[{\"arch\":\"arm64-v8a\"}]}" >> $GITHUB_OUTPUT
             echo "profile=blank-test" >> $GITHUB_OUTPUT
          else
            # dev, preview - default to arm64-v8a
            echo "matrix={\"include\":[{\"arch\":\"arm64-v8a\"}]}" >> $GITHUB_OUTPUT
            echo "profile=$BUILD_TYPE" >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    runs-on: blacksmith-2vcpu-ubuntu-2404
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    permissions:
      contents: write
      pull-requests: write
      packages: read
    env:
      BUILD_TYPE: ${{ needs.setup.outputs.buildType }}
      EAS_PROFILE: ${{ needs.setup.outputs.profile }}
      ABI_FILTERS: ${{ matrix.arch }}
      EAS_LOCAL_BUILD_SKIP_CLEANUP: 1

    environment: ${{ (github.event_name == 'pull_request' && 'production') || null }}

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5
        with:
          ref: ${{ needs.setup.outputs.commitSha }}
          fetch-depth: 0 # 获取完整历史记录以计算 commit 数量

      - name: 🤖 Setup PNPM
        uses: pnpm/action-setup@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}
          packager: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: ⚙️ Prepare Variables
        id: prepare-vars
        run: |
          APP_VERSION=$(node -p "require('./apps/mobile/package.json').version")
          VERSION_CODE=$(git rev-list --count HEAD)

          # e.g. bbplayer-v1.0.0-prod-arm64-v8a
          APK_NAME="bbplayer-v${APP_VERSION}-${{ env.BUILD_TYPE }}-${{ matrix.arch }}"
          ARTIFACT_DIR="${RUNNER_TEMP}/${APK_NAME}"

          mkdir -p "$ARTIFACT_DIR"

          echo "APK_NAME=${APK_NAME}" >> $GITHUB_ENV
          echo "ARTIFACT_DIR=${ARTIFACT_DIR}" >> $GITHUB_ENV
          echo "APK_TEMP_PATH=${ARTIFACT_DIR}/${APK_NAME}.apk" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_WORKINGDIR=${RUNNER_TEMP}/eas-local-build-${{ matrix.arch }}" >> $GITHUB_ENV
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV

          echo "apkName=${APK_NAME}" >> $GITHUB_OUTPUT
          echo "artifactDir=${ARTIFACT_DIR}" >> $GITHUB_OUTPUT

      - name: ⚙️ Prepare Firebase Config
        env:
          FIREBASE_ANDROID_JSON_B64: ${{ secrets.FIREBASE_ANDROID_JSON_B64 }}
        if: ${{ env.FIREBASE_ANDROID_JSON_B64 != '' }}
        run: |
          mkdir -p apps/mobile/assets/config/google-services
          echo "$FIREBASE_ANDROID_JSON_B64" | base64 -d > apps/mobile/assets/config/google-services/google-services.real.json

      - name: 🚀 Build APK
        if: env.BUILD_TYPE != 'blank-test'
        run: cd apps/mobile && eas build --platform android --profile ${{ env.EAS_PROFILE }} --local --no-wait --output="$APK_TEMP_PATH"

      - name: 🧪 Create Dummy APK
        if: env.BUILD_TYPE == 'blank-test'
        run: |
          echo "Dummy APK $APK_NAME" > "$APK_TEMP_PATH"

      - name: 🚀 Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.prepare-vars.outputs.apkName }}
          path: ${{ steps.prepare-vars.outputs.artifactDir }}
          if-no-files-found: error

  release:
    needs: [setup, build]
    if: needs.setup.outputs.buildType == 'prod' || needs.setup.outputs.buildType == 'blank-test'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5
        with:
          ref: ${{ needs.setup.outputs.commitSha }}

      - name: 📥 Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: ⚙️ Prepare Release Variables
        run: |
          APP_VERSION=$(node -p "require('./apps/mobile/package.json').version")
          RELEASE_TAG="v${APP_VERSION}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          ls -R dist/

      - name: 🎁 Create Release
        run: |
          mapfile -t FILES < <(find dist -type f -name "*.apk" | sort)

          gh release create "$RELEASE_TAG" \
            "${FILES[@]}" \
            --title "$RELEASE_TAG" \
            --draft \
            --notes "auto release by GitHub Actions"

  notify:
    needs: [setup, build]
    if: always() && github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Send build status notification
        uses: actions/github-script@v8
        with:
          script: |
            const buildResult = "${{ needs.build.result }}";
            const buildType = "${{ needs.setup.outputs.buildType }}";
            const commitSha = "${{ needs.setup.outputs.commitSha }}";
            const prNumber = "${{ needs.setup.outputs.prNumber }}";
            const runUrl = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            const mention = "${{ env.MENTION_USER }}";

            const icon = buildResult == 'success' ? '✅' : '❌';
            const title = buildResult == 'success' ? `构建软件包成功` : `构建软件包失败`;

            let body = `
            ## ${icon} ${title} (${buildType})

            ${mention}, 新版触发的构建已经完成

            - **状态:** ${buildResult}
            - **提交:**
            ${commitSha.substring(0, 7)}
            - **详细信息:** [Workflow](${runUrl})
            `;

            if (prNumber) {
              body += `\n- **触发事件:** PR #${prNumber}`;
              try {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: body
                });
              } catch (e) {
                console.error(`Failed to comment on PR: ${e.message}.`);
              }
            }
