name: 'PR Checks'

on: pull_request

jobs:
  lint:
    name: 🚨 Lint Codebase
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5

      - uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@26
          cache: true

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🕵️ Check Dependencies
        run: pnpm check:deps

      - name: 🚀 Run Lint
        # 需要生成 expo router 的类型来进行类型检查
        run: |
          cd ./apps/mobile && npx expo customize tsconfig.json && cd ../../
          pnpm lint
